version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
